public class AritmaticCalculations {
    public void Addition( integer x , integer y) {
        integer z = x+y;
        system.debug('The result is ' + z);
    }
    public void Subtraction(integer x , integer y){
          integer z = x - y;
    system.debug('The result is ' + z);
    }
    public void Multiplication(integer x, integer y, integer m){
        integer z = x * y *m;
        system.debug('The result is ' + z);
    }
}
