public class primitiveDataTypeDemo3 {
    public void printNewDateTime(){
Datetime dt3 = Datetime.newInstance(2021, 5, 15, 9, 5, 40);
System.debug('dt3 is ' + dt3);

Datetime dt4_1 = datetime.newInstance(300000);
System.debug('dt4_1 is ' + dt4_1);

Long longTime = 2541454155214545L;
datetime dt4 = datetime.newInstance(longtime);
System.debug('dt4 is ' + dt4);

datetime dt6 = datetime.now();
System.debug('dt 6 current datetime is ' + dt6);

Datetime dt5 = Datetime.newInstanceGMT(1998, 8, 4, 5, 1, 4);
System.debug('dt4 is ' + dt5);


    }
}
