public class SalesforceDeveloper {
    public void MyFirstCode() {
        string MyfavouriteCountry = 'My favourite Country is Edirne';
        system.debug(MyfavouriteCountry);
        string MyfavouriteFilm = 'My favourite film is Indiana Johns';
        system.debug(MyfavouriteFilm);
        string MyFavouriteSeosan = 'My favourite season is Summer';
        system.debug(MyFavouriteSeosan);

    }
    public void myFouvites(){
        string Mytown = 'Istanbul';
        System.debug(Mytown);
        integer myFavouriteNumber = 7;
        System.debug(myFavouriteNumber);
        system.debug('My favourite town is ' + Mytown + ', ' + 'My favourite number is ' + myFavouriteNumber);
    }
}
