public  class StudentMarksheet {
    public void showMarksheetUsingDatatype(){
        string firstName = 'Bülent';
        string lastName = 'Kurt';
        integer Mathematics = 90;
        integer English = 100;
        integer Chemistry =95;
        system.debug(firstName + ' ' + lastName + ', Math grade is ' + Mathematics + ', English grade is ' + English + ', Chemistry grade is ' + Chemistry);
    }
    public void showMarksheetUsingObject(){
        Object firstName = 'Bulent';
        Object lastName = 'Kurt';
        Object Mathematics = 90;
        Object English = 100;
        Object Chemistry = 95;
        system.debug(firstName + ' ' + lastName + ', Math grade is ' + Mathematics + ', English grade is ' + English + ', Chemistry grade is ' + Chemistry);
      
    }
    }

