// •	Write an SOQL query for contact Object querying Account object fields in the same query referring ID and Name and pass them to a list<Contact> lstcontact records.
// •	Run the above the over the for loop and display the account id and account name.
// •	Write an SOQL query for Account Object querying contact object fields in the same query referring ID and Name and pass them to a list<Account> lstaccount records.
// •	Run the above the over the for loop and display the Contact id and Contact name.

SoqlAssig01December.listOfContact();