MathPractice Ttl = new MathPractice();
system.debug(Ttl.practiceFive(5, 5));
system.debug(Ttl.practiceFive(5, 9));
system.debug(Ttl.practiceFive(0, -2));
system.debug(Ttl.practiceFive(-1, -3));
system.debug(Ttl.practiceFive(-3, -1));

// string plnt = MathPractice.Space();
// MathPractice plnt = new MathPractice();
// system.debug(plnt);
MathPractice.Space();

list<string> account = new list<string>{'veli', 'ayşe'};
 account.add('ali');

 system.debug( GeneralList.toCaps(account));